version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    links:
      - db
    depends_on:
      - db

  flask_client:
    build:
      context: .
      dockerfile: flask_client/Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./flask_client:/scraper